---
title: "Zamudio lab coding tips and tricks"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### This document is a compilation of bioinformatic and coding resources that we find useful.

#### It has been collaboratively generated by past and present members of the lab, including [Cait McDonald](https://caitmcdonald.github.io/){:target="_blank"}, ...

-----

#### Find help with:

1. [Command line](#Command-line-basics)
1. [Accessing Cornell BioHPC]()
1. [Slurm](https://github.com/caitmcdonald/parallel_computing/blob/master/slurm_scripting.md){:target="_blank"}
1. [git and Github](https://github.com/caitmcdonald/Zamudio_git_intro/blob/master/README.md){:target="_blank"}
1. [R tricks](#R-tricks)
1. [Version controlled project management with `workflowr`](https://jdblischak.github.io/workflowr/index.html){:target="_blank"}


-----

#### Command line basics:

1. [Downloading and installing software](#Downloading-and-installing)
1. [Navigating directories](#Navigating directories)
1. [Viewing directories](#Viewing-files)
1. [Viewing files](#Viewing-files)
1. [Viewing program progress](#Viewing-program-progress)

<br>

__Downloading and installing software__

Install software:
```
sudo apt-get install <software_name>
```
<br>


Femove software:
```
sudo apt-get --purge remove <software_name>
```
<br>

Update one application only:
```
sudo apt-get --only-upgrade install <software_name>
```
<br>

Retrieve web content:
```
curl -o "url[range]" -o <outputfile_#1.txt> 
```
(You can include range or list of elements with [] for sequential or {} if not)

<br>

__Navigating directories__

See command line history:
```
history
```
<br>


__Viewing directories__

Files in a directory, human-readable:
```
ls -lh
```
<br>

Size of current directory (BioHPC):
```
lfs-du -h .
```
<br>

Size of files in directory, sorted by size (BioHPC):
```
lfs-du -h $DIR/* | sort -hr
```
<br>


__Viewing files__

View a file in terminal (only loads a portion of file in memory at a time):
```
less <filename>
```
<br>

Create and edit a file within terminal:
```
nano <filename>
```
<br>

Open a file in your default editor:
```
edit <filename>
```
<br>


__Viewing program progress__

View all programs you have running:
```
top -u <username>
```
<br>

View output file as it's being written:
```
tail -f <filename>
```

<br>

-----


#### R tricks
